language: php
php:
  - '5.6'
  - '7.0'

before_script:
   - composer install

script: phpunit --coverage-clover=coverage.clover

notifications:
  email: false
  irc:
    channels:
        secure: "B+0BkpJH9k+WNuyChB4B5KORDqxj9SmsMSn3eaelDxhfJSZVagVToj1qtZUHqar3Bh7jKnT1/JD7PS/WFDGVMlkFftDae0cYoVXxbW32lUS3iNwJAWEmLqKIeYiMIt0+WTK8FKYc8u8KhtVVCG4RnUreofR3urj/z5mAxEqAUqk="
    on_success: change
    on_failure: always
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover


sudo: false
